kolla_globals_config:
  kolla_base_distro: "{{ kolla_docker_distro }}"
  kolla_install_type: 'binary'
  openstack_release: "{{ kolla_version }}"
  docker_registry: "{{ docker_registry.fqdn }}:{{ docker_registry.port }}"
  enable_keystone_v3: "no"
  keystone_admin_user: 'admin'
  contrail_api_interface_address: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
  kolla_external_vip_address: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
  kolla_internal_vip_address: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
  kolla_external_vip_interface: eth0
  network_interface: eth0
  api_interface: eth0
  neutron_external_interface: eth0
  neutron_plugin_agent: opencontrail
  rabbitmq_user: openstack
  contrail_docker_registry: "{{ docker_registry.fqdn }}:{{ docker_registry.port }}"
  enable_nova_compute: 'yes'
  enable_haproxy: 'no'
  # override rabbitmq ports to prevent conflict with the contrail rabbit instance
  rabbitmq_port: "5673"
  rabbitmq_management_port: "15673"
  rabbitmq_cluster_port: "25673"
  rabbitmq_epmd_port: "4370"
  openstack_service_workers: 1
