- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "http://logs.openstack.org"

- hosts: all
  roles:
    - add-build-sshkey
    - configure-hosts-entries
    - validate-host
    - repo-sandbox-prepare
