- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "http://logs.opencontrail.org"

- hosts: all
  roles:
    - contrail-common-libs
    - add-build-sshkey
    - start-zuul-console
    - configure-hosts-entries
    - validate-host
- hosts: all
  roles:
    - role: configure-hosts-entries
      hosts_entries:
        - fqdn: "{{ ansible_fqdn }}"
          address: "{{ ansible_all_ipv4_addresses[0] }}"
