- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "http://logs.opencontrail.org"

- hosts: all
  roles:
    - add-build-sshkey
    - configure-hosts-entries
    - configure-mirrors
    - validate-host
    - prepare-workspace
