- hosts: jluk-xenial
  vars:
    reponame: "{{ zuul.build }}"
  roles:
    - prepare-debs
- hosts: "{{ site_deb.fqdn }}"
  vars:
    reponame: "{{ zuul.build }}"
  roles:
    - upload-debs
- hosts: jluk-xenial
  vars:
    reponame: "{{ zuul.build }}"
  roles:
    - publish-debs
